name: GitHub Classroom Workflow
on: [push]

jobs:
  build:
    name: Autograding
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # TODO build, test and deploy project
#       - name: Build, Push and Release a Docker container to Heroku. # Your custom step name
#         uses: gonuit/heroku-docker-deploy@v1.3.3 # GitHub action name (leave it as it is).
#         with:
#           email:  "alex-rudenkiy@mail.ru"
#           heroku_api_key: 22b1b640-f541-4b04-b267-5356f8bcdaec 
#           heroku_app_name: "rating-system-alex"
#           dockerfile_directory: "./Rating System"
#           dockerfile_name: Dockerfile
#           docker_options: "--no-cache"
#           process_type: "web"    
      - name: Build and push Docker to Heroku
        env:
          HEROKU_APP_NAME: "rating-system-alex"
          DOCKERFILE_DIRECTORY: "./Rating System"
          HEROKU_EMAIL: alex-rudenkiy@mail.ru
          HEROKU_API_KEY: 22b1b640-f541-4b04-b267-5356f8bcdaec
          DOCKERFILE_NAME: "Dockerfile"
          DOCKER_OPTIONS: "--no-cache"
        run: |
          cd ${DOCKERFILE_DIRECTORY}
          echo ${HEROKU_API_KEY} | docker login \
            --username=${HEROKU_EMAIL} \
            registry.heroku.com \
            --password-stdin
          docker build \
            --file ${DOCKERFILE_NAME} \
            ${DOCKER_OPTIONS} \
            --tag registry.heroku.com/${HEROKU_APP_NAME}/web .
          heroku container:push web --app ${HEROKU_APP_NAME}
          heroku container:release web --app ${HEROKU_APP_NAME}
          
      - name: Run API Tests
        id: run-newman
        uses: anthonyvscode/newman-action@v1
        with:
          # TODO insert your variant
          collection: 4/postman/[rsoi] postman_collection.json
          environment: 4/postman/[rsoi][heroku] postman_environment.json
          delayRequest: 50
          reporters: cli

      - uses: education/autograding@v1
        id: autograder
        continue-on-error: true
