name: GitHub Classroom Workflow
on: [push]

jobs:
  startBuild:
    name: Autograding
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

  testing:
    name: Testing Microservice
    runs-on: self-hosted
    steps:
      - name: Run API Tests
        id: run-newman
        uses: anthonyvscode/newman-action@v1
        with:
          workingDir: "./v4/postman/"
          # TODO insert your variant
          collection: "[rsoi] postman_collection.json"
          environment: "[rsoi][heroku] postman_environment.json"
          delayRequest: 50
          reporters: cli

      - uses: education/autograding@v1
        id: autograder
        continue-on-error: true
